name: 🐞 Bug Report
description: Report a bug or issue with the game.
title: "[Bug] "
labels: ["bug", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## 🐞 Bug Report — Pokémon TestFlight
        Please provide details about the bug or issue you encountered.

  - type: textarea
    id: description
    attributes:
      label: 📄 Description of the Bug
      description: Provide a clear and concise description of the bug.
      placeholder: Example: The application crashes when I try to save my progress.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: 🛠 Steps to Reproduce
      description: Provide steps to reproduce the bug. This will help us identify the issue.
      placeholder: Example: 1. Go to menu 2. Click on 'Save' 3. Observe the crash
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: 🎯 Expected Behavior
      description: What did you expect to happen?
      placeholder: Example: The game should save my progress without crashing.

  - type: textarea
    id: actual
    attributes:
      label: 💥 Actual Behavior
      description: What actually happened?
      placeholder: Example: The game crashes with an error message stating "Save failed."

  - type: textarea
    id: environment
    attributes:
      label: 🌍 Environment
      description: Include any relevant information about the environment where the bug occurs.
      placeholder: Example: Windows 10, version 20H2, Game version 1.0.0

  - type: checkboxes
    id: checklist
    attributes:
      label: ✅ Checklist Before Submitting
      description: Please confirm the following.
      options:
        - label: I have searched the existing issues for similar reports.
          required: true
        - label: I have provided detailed steps to reproduce the bug.
          required: true

