name: 💡 QOL Suggestion
description: Suggest quality-of-life improvements for Pokémon TestFlight.
title: "[QOL] "
labels: ["quality of life", "enhancement"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## 💡 Quality of Life Suggestion — Pokémon TestFlight
        Suggest non-critical improvements that make the game smoother, easier to use, or more intuitive.

  - type: textarea
    id: description
    attributes:
      label: 📄 Description of the Suggestion
      description: What QOL change would you like to suggest?
      placeholder: Example: Add a quick-save button in the menu.
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: 🎯 Why This Suggestion?
      description: How would this improve the game experience?
      placeholder: This would help because...

  - type: textarea
    id: alternatives
    attributes:
      label: 🔄 Alternatives (Optional)
      description: Any other solutions or approaches?
      placeholder: Alternative ideas could be...

  - type: checkboxes
    id: checklist
    attributes:
      label: ✅ Checklist
      description: Confirm before submitting.
      options:
        - label: This is not a bug report.
          required: true
        - label: This is not a feature request for major content.
          required: true
        - label: I’ve checked if this QOL suggestion has already been submitted.
          required: true
