name: 🔧 Technical Help / Support
description: Request help with running the game, installation issues, or crashes unrelated to gameplay bugs.
title: "[Tech Help] "
labels: ["support", "technical help"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## 🔧 Technical Help / Support — Pokémon TestFlight
        Use this form if you're having trouble installing, running, or loading the game. This is **not** for in-game bug reports.

  - type: textarea
    id: description
    attributes:
      label: 🛠️ Issue Description
      description: What is happening? Are you seeing an error message, crash, or is the game failing to launch?
      placeholder: Describe the issue you're facing.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: 🧠 Troubleshooting Steps Taken
      description: Have you tried anything to fix it? (Example: re-downloading, restarting, etc.)
      placeholder: I tried...

  - type: input
    id: system
    attributes:
      label: 🖥️ System Info
      description: OS and version (Example: Windows 10, Mac, SteamDeck, etc.)
      placeholder: Example: Windows 11

  - type: input
    id: game_version
    attributes:
      label: 💻 Game Version
      description: What game version are you using?
      placeholder: Example: v0.1a

  - type: textarea
    id: crash_log
    attributes:
      label: 📜 Crash Log or Error (If Any)
      description: If there is a crash log or error message, paste it here or attach a screenshot.
      placeholder: Paste the error message or log here.

  - type: checkboxes
    id: checklist
    attributes:
      label: ✅ Checklist
      description: Confirm this isn’t a bug report.
      options:
        - label: This is not an in-game bug report.
          required: true
